# Generated by Django 5.1.1 on 2024-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahawaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kahawaapp',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kahawaapp',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
