# Generated by Django 5.1.1 on 2024-09-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahawaapp', '0002_product_delete_kahawaapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kahawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='kahawa/')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
