# Generated by Django 5.1.1 on 2024-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahawaapp', '0002_alter_kahawaapp_quantity_alter_kahawaapp_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kahawaapp',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='kahawaapp',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
