# Generated by Django 5.1.1 on 2024-10-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kahawaapp', '0003_kahawa_delete_product'),
        ('kahawaapp', '0003_rename_quantity_kahawaapp_quantity_and_more'),
    ]

    operations = [
    ]
