# Generated by Django 5.1.1 on 2024-10-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kahawaapp', '0005_kahawaapp_delete_kahawa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kahawaapp',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='kahawaapp',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='kahawaapp',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
